[[redirects]]
  from = "/category/*"
  to = "/tag/:splat"
  status = 301

[[redirects]]
  from = "wp-content/uploads/*"
  to = "/_images/:splat"
  status = 301

[[redirects]]
  from = "docs/*"
  to = "/_files/:splat"
  status = 301

[[redirects]]
  from = "downloads/*"
  to = "/_files/:splat"
  status = 301

[[redirects]]
  from = "/work"
  to = "/posts/"
  status = 301

[[redirects]]
  from = "/feed"
  to = "/posts/"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/"
  status = 302

[[redirects]]
  from = "/feed.xml"
  to = "/rss.xml"
  status = 301

[[redirects]]
  from = "/type/*"
  to = "/posts/"
  status = 301

[[redirects]]
  from = "/archives/tags/"
  to = "/tags/"
  status = 301

[[redirects]]
  from = "/archives/all/"
  to = "/posts/"
  status = 301

[[redirects]]
  from = "/resume"
  to = "https://www.linkedin.com/in/joshcanhelp"
  status = 302

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

[[redirects]]
  from = "https://joshcanhelp.netlify.com/*"
  to = "https://www.joshcanhelp.com/:splat"
  status = 301

