[[redirects]]
  from = "/category/*"
  to = "/tag/:splat"
  status = 301

[[redirects]]
  from = "wp-content/uploads/*"
  to = "/_images/:splat"
  status = 301

[[redirects]]
  from = "/work"
  to = "/archives/all/"
  status = 302

[[redirects]]
  from = "/contact"
  to = "/"
  status = 302

[[redirects]]
  from = "/type/*"
  to = "/archives/all/"
  status = 302

[[redirects]]
  from = "/resume"
  to = "https://www.linkedin.com/in/joshcanhelp"
  status = 302

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

[[redirects]]
  from = "http://joshcanhelp.netlify.com/*"
  to = "http://www.joshcanhelp.com/:splat"
  status = 301

[[redirects]]
  from = "http://joshcanhelp.com/*"
  to = "http://www.joshcanhelp.com/:splat"
  status = 301
